In [125]:
import numpy as np

In [127]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [129]:
d=[]
for i in h:
    d.append(i+5)

In [131]:
d

[35, 25, 10, 13, 14]

In [137]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [145]:
arr=np.array([20,50,30,70,80,40,36,54,23,98])


In [151]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [153]:
arr+5

array([ 25,  55,  35,  75,  85,  45,  41,  59,  28, 103])

In [155]:
arr*100

array([2000, 5000, 3000, 7000, 8000, 4000, 3600, 5400, 2300, 9800])

In [157]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [159]:
arr>50

array([False, False, False,  True,  True, False, False,  True, False,
        True])

In [161]:
arr[arr>50]

array([70, 80, 54, 98])

In [167]:
arr[4:-1:2]

array([80, 36, 23])

In [169]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [171]:
k

[36, 4, 9, 81, 49, 25, 64]

In [173]:
arr[arr>50]

array([70, 80, 54, 98])

In [175]:
np.where(arr>50)

(array([3, 4, 7, 9], dtype=int64),)